import assert from 'node:assert/strict';
import test from 'node:test';
import { collectReleases, parseGitLog, renderChangelog } from './generate-changelog.mjs';

const commits = parseGitLog([
  '1111111\t2026-01-01\tfeat(tube-vault): first feature',
  '2222222\t2026-01-02\tbuild(tube-vault): v1.0.0',
  '3333333\t2026-01-03\tbuild(tube-vault): v1.0.1',
  '4444444\t2026-01-04\tfix: repair publication',
  '5555555\t2026-01-04\tdocs: explain recovery',
  '6666666\t2026-01-04\tdocs(tube-vault): regenerate changelog',
  '7777777\t2026-01-04\tdocs(tube-vault): refresh changelog',
].join('\n'));

test('collectReleases uses release commits as boundaries and skips empty releases', () => {
  assert.deepEqual(collectReleases(commits), [
    { version: null, commits: commits.slice(3, 5) },
    { version: '1.0.0', commits: commits.slice(0, 1) },
  ]);
});

test('renderChangelog groups commits and normalizes generated prose', () => {
  const output = renderChangelog(collectReleases(commits, '1.0.2'));
  assert.match(output, /^# Changelog\n\n<!-- Generated by `npm run changelog`\. Do not edit manually\. -->/);
  assert.match(output, /## v1\.0\.2/);
  assert.match(output, /### Fixed\n\n- Repair publication\./);
  assert.match(output, /### Documentation\n\n- Explain recovery\./);
  assert.doesNotMatch(output, /v1\.0\.1/);
});

test('collectReleases rejects invalid, duplicate, and empty releases', () => {
  assert.throws(() => collectReleases(commits, '1.0'), /Expected --version/);
  assert.throws(() => collectReleases(commits, '1.0.0'), /already has a release commit/);
  assert.throws(() => collectReleases(commits.slice(0, 3), '1.0.2'), /No changes exist/);
});
